const mongoose=require('mongoose')

const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        maxLength:25
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
    },
    profImg:{
        type:String,
        default:"./assets/grey.png"
    },
    backgroundImg:{
        type:String,
        default:"./assets/grey.png"
    },
    discription:{
        type:String,
        default:''
    },
    about:{
        nickname:{
            type:String,
            default:''
        },
        gender:{
            type:String,
            default:''
        },
        dob:{
            type:String,
            default:''
        },
        profile:{
            type:String,
            default:''
        },
        work:{
            type:String,
            default:''
        },
        curlocation:{
            type:String,
            default:''
        },
        hometown:{
            type:String,
            default:''
        },
        secondary:{
            type:String,
            default:''
        },
        hs:{
            type:String,
            default:''
        },
        graduation:{
            type:String,
            default:''
        },
        masters:{
            type:String,
            default:''
        }
    },
    followers:{
        type:Array,
        default:[]
    },
    following:{
        type:Array,
        default:[]
    },
    isfollowing:{
        type:Map,
        of:Boolean
    },
    notifications:{
        type:Array,
        default:[]
    },
    newnotification:{
        type:Boolean,
        default:false
    }
},{timestamps:true});
    
module.exports=mongoose.model('user',userSchema);